### ISSUE TITLE
[Request] Add Kubeflow as the way to run TensorFlow distributed training jobs on Kubernetes

### ISSUE THREAD

**Issue by gaocegege** [tensorflow/ecosystem#79]
Hi, I am from [Kubeflow community](https://github.com/kubeflow), which is an open source community dedicated to making using ML stacks on Kubernetes easy, fast and extensible.

We implemented [an operator for TensorFlow on Kubernetes](https://github.com/kubeflow/tf-operator). Personally, I think the CRD defined in the operator is ease to use and understand compared to the jinja template. Here is one example:

```yaml
apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: "example-job"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
restartPolicy: OnFailure
```

I am wondering if we could add our implementation in the repository to enrich the ecosystem of TensorFlow and Kubernetes.

Welcome your suggestions!

/cc @ddysher @jlewi @DjangoPeng @ScorpioCPH
